export enum Errors {
  API_ERROR = 'API_ERROR',
  JOI_SCHEMA_NOT_FOUND = 'JOI_SCHEMA_NOT_FOUND',
  DEPENDENCY_FILE_NOT_FOUND = 'DEPENDENCY_FILE_NOT_FOUND',
  DEPENDENCY_FILE_IS_INVALID = 'DEPENDENCY_FILE_IS_INVALID',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  CANNOT_GET_REGISTRY_METADATA = 'CANNOT_GET_REGISTRY_METADATA',
  CANNOT_SEND_MAIL = 'CANNOT_SEND_MAIL',
}
